# Generated by Django 5.0.7 on 2025-09-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('current_price_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'ordering': ['cryptocurrency'],
            },
        ),
        migrations.CreateModel(
            name='SupportedCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('max_purchase_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15)),
                ('network_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CryptoPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='crypto.cryptorate')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['crypto_rate', 'timestamp'], name='crypto_cryp_crypto__f546ab_idx')],
            },
        ),
    ]
